theme="dark_plus"

[editor]
true-color = true

[editor.soft-wrap]
enable = true

[editor.smart-tab]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
center = ["diagnostics"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type", ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
tab = "all"

