# theme="dark_plus"
# theme = "new_moon"
theme = "fleet_dark"
# theme = "ao"
# theme = "pop-dark"

[editor]
true-color = true

[editor.soft-wrap]
enable = true

[editor.smart-tab]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
center = ["diagnostics"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type", ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# [editor.whitespace]
# render = "all"

# [editor.whitespace.render]
# space = "none"
# tab = "all"
# nbsp = "all"
# nnbsp = "all"
# newline = "all"
# tabpad = "all"


[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "-"

[keys.normal]
"," = []
"." = ["global_search"]
A-x = "extend_to_line_bounds"
"A-с" = ["change_selection_noyank"]
"A-і" = ["split_selection_on_newline"]
C-n = ["move_line_down", "scroll_down"]
C-p = ["move_line_up", "scroll_up"]
C-y = "yank_to_clipboard"
"C-а" = ["page_down"]
"C-в" = ["page_cursor_half_down"]
"C-г" = ["page_cursor_half_up"]
"C-и" = ["page_up"]
"C-ш" = ["jump_forward"]
"C-щ" = ["jump_backward"]
"C-і" = ["save_selection"]
X = ["extend_line_up", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]
"І" = ["split_selection"]
"А" = ["find_prev_char"]
"Б" = []
"Г" = ["redo"]
"Е" = ["till_prev_char"]
"З" = ["paste_clipboard_before"]
"И" = ["move_prev_long_word_start"]
"Й" = ["record_macro"]
"К" = ["replace_selections_with_clipboard"]
"Л" = ["keep_selections"]
"Н" = ["yank_main_selection_to_clipboard"]
"О" = ["join_selections"]
"П" = ["goto_line"]
"С" = []
"Т" = ["search_prev"]
"У" = []
"Ф" = ["insert_at_line_end"]
"Ц" = ["move_next_long_word_start"]
"Ч" = ["extend_to_line_bounds"]
"Ш" = ["insert_at_line_start"]
"Щ" = ["open_above"]
"Ь" = []
"Ю" = []
"а" = ["find_next_char"]
"б" = []
"в" = ["delete_selection"]
"г" = ["undo"]
"д" = ["move_char_right"]
"е" = ["find_till_char"]
"з" = ["paste_clipboard_after"]
"и" = ["move_prev_word_start"]
"й" = ["replay_macro"]
"к" = ["replace"]
"л" = ["move_visual_line_up"]
"м" = ["select_mode"]
"н" = ["yank_to_clipboard"]
"о" = ["move_visual_line_down"]
"п" = []
"р" = ["move_char_left"]
"с" = ["change_selection"]
"т" = ["search_next"]
"у" = ["move_next_word_end"]
"ф" = ["append_mode"]
"х" = []
"ц" = ["move_next_word_start"]
"ч" = ["extend_line_below"]
"ш" = ["insert_mode"]
"щ" = ["open_below"]
"ь" = []
"ю" = []
"і" = ["select_regex"]
"ї" = []

[keys.select]
A-x = "extend_to_line_bounds"
"A-ч" = ["extend_to_line_bounds"]
C-y = "yank_to_clipboard"
"C-н" = "yank_to_clipboard"
X = ["extend_line_up", "extend_to_line_bounds"]
"Ч" = ["extend_line_up", "extend_to_line_bounds"]
"р" = ["extend_char_left"]
"л" = ["extend_line_up"]
"о" = ["extend_line_down"]
"д" = ["extend_char_right"]
"с" = ["change_selection"]
"в" = ["delete_selection"]
