[manager]
ratio          = [ 1, 3, 5 ]
sort_by        = "modified"
sort_sensitive = false
sort_reverse   = true
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[preview]
tab_size   = 3
max_width  = 600
max_height = 900
cache_dir  = "~/.cache/yazi"

[opener]
folder = [
	{ run = 'kde-open "$@"', desc = "Reveal in Finder" },
	{ run = '$EDITOR "$@"', block = true, desc = "Editor" },
]
archive = [
	{ run = 'unar "$1"', desc = "Extract here" },
	{ run = '$EDITOR "$@"', block = true, desc = "Editor" },
]
text = [
	{ run = '$EDITOR "$@"', block = true, desc = "Editor" },
	{ run = '"$@"', block = true, desc = "run"},
  { run = 'open "$@"', block = true, desc = "Default app" },
]
image = [
	{ run = 'kde-open "$@"', desc = "Open" },
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF" },
]
video = [
	{ run = 'haruna "$@"' },
	{ run = 'vlc "$@"' },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
audio = [
	{ run = 'elisa "$@"' },
	{ run = 'vlc "$@"' },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
fallback = [
	{ run = 'kde-open "$@"', desc = "Open" },
	{ run = 'open -R "$@"', desc = "Reveal in Finder" },
	{ run = '$EDITOR "$@"', block = true, desc = "Editor" },
]

[open]
rules = [
	{ name = "*/", use = "folder" },

	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "inode/x-empty", use = "text" },

	{ mime = "application/json", use = "text" },
	{ mime = "*/javascript", use = "text" },

	{ mime = "application/zip", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
	{ mime = "application/x-rar", use = "archive" },
  
	{ mime = "*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false
